class Solution(object):
    def singleNumber(self, nums):
        # Initialize the unique number...
        uniq_num = 0
        # Traverse all elements through the loop...
        for idx in nums:
            # Concept of XOR...
            uniq_num ^= idx
        return uniq_num       # Return the unique number...